name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - master

# Variables
# Set Java version
env:
  JAVA_VERSION: '17'
  GRADLE_VERSION: '8.8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Install SDKMAN and Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle ${{ env.GRADLE_VERSION }}

      - name: Run publich task
        run: make publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Maven artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: dist/*

      - name: Run build task
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Maven artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-artifacts
          path: maven-artifacts

      - name: Prepare export directory
        run: |
          mkdir -p export-maven-repo
          cp -r maven-artifacts/* export-maven-repo/

      - name: Deploy to GitHub Pages (merge)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: export-maven-repo
          publish_branch: gh-pages
          keep_files: true